stages:
  - build
  - test
  - deploy

build:
  stage: build
  script:
    - echo "Building the script..."

test:
  stage: test
  script:
    - echo "Running the script..."

deploy:
  stage: deploy
  script:
    - echo "Deploying the script"
